version: '3.8'

services:
  atlas:
    image: alisinabh/atlas
    ports:
      - "8080:8080"
    environment:
      MAXMIND_ACCOUNT_ID: ${MAXMIND_ACCOUNT_ID}
      MAXMIND_LICENSE_KEY: ${MAXMIND_LICENSE_KEY}
    volumes:
      - ./data:/opt/atlas/db
